title: Rocky Horror with the Bawdy Caste
tagline: "Rocky Horror with the Bawdy Caste"
email: info@bawdycaste.com
description: "San Francisco's Rocky Horror Picture Show Shadow Cast, live at the Balboa Theater the last Saturday of every month!"
permalink: /:categories/:year/:month/:day/:title/
url: "https://bawdycaste.com"
logo: https://storage.googleapis.com/bawdycaste/images/bawdycaste_logo.png
image: https://storage.googleapis.com/bawdycaste/images/facebook-header.jpg
locale: en_US

facebook:
  publisher: https://www.facebook.com/bawdycaste

collections:
  shows:
    output: true
    permalink: /:collection/:name/

twitter:
  username: bawdycaste
  card: summary

social:
  name: Bawdy Caste
  links:
    - https://twitter.com/bawdycaste
    - https://www.facebook.com/bawdycaste
    - https://www.instagram.com/bawdycaste
    - https://github.com/bawdycaste

github_username: bawdycaste
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  load_paths:
    - vendor/bundle/ruby/3.2.0/gems/bootstrap-5.3.5/assets/stylesheets
    - vendor/bundle/ruby/3.2.0/gems/bootstrap-5.3.8/assets/stylesheets
    - vendor/bundle/ruby/3.4.0/gems/bootstrap-5.3.5/assets/stylesheets
    - vendor/bundle/ruby/3.4.0/gems/bootstrap-5.3.8/assets/stylesheets
    - vendor/bundle/ruby/4.0.0/gems/bootstrap-5.3.5/assets/stylesheets
    - vendor/bundle/ruby/4.0.0/gems/bootstrap-5.3.8/assets/stylesheets